use recipes;

INSERT INTO ingredients VALUES (null,'Яйцо куриное');
INSERT INTO ingredients VALUES (null,'Яйцо перепелиное');
INSERT INTO ingredients VALUES (null,'Хлеб ржано-пшеничный');
INSERT INTO ingredients VALUES (null,'Хлеб пшеничный');
INSERT INTO ingredients VALUES (null,'Хлеб ржаной');
INSERT INTO ingredients VALUES (null,'Сушки');
INSERT INTO ingredients VALUES (null,'Сухари');

INSERT INTO ingredients VALUES (null,'Булочка');
INSERT INTO ingredients VALUES (null,'Батон нарезной');
INSERT INTO ingredients VALUES (null,'Баранки');
INSERT INTO ingredients VALUES (null,'Виноград');
INSERT INTO ingredients VALUES (null,'Малина');
INSERT INTO ingredients VALUES (null,'Арбуз');
INSERT INTO ingredients VALUES (null,'Лимон');
INSERT INTO ingredients VALUES (null,'Персик');
INSERT INTO ingredients VALUES (null,'Яблоки');
INSERT INTO ingredients VALUES (null,'Апельсин');
INSERT INTO ingredients VALUES (null,'Слива');
INSERT INTO ingredients VALUES (null,'Вишня');
INSERT INTO ingredients VALUES (null,'Пюре яблочное');
INSERT INTO ingredients VALUES (null,'Вишня консервированная');
INSERT INTO ingredients VALUES (null,'Компот');
INSERT INTO ingredients VALUES (null,'Клубника');
INSERT INTO ingredients VALUES (null,'Варенье из клубники');
INSERT INTO ingredients VALUES (null,'Вишневое варенье');
INSERT INTO ingredients VALUES (null,'Варенье из яблок');
INSERT INTO ingredients VALUES (null,'Соль');
INSERT INTO ingredients VALUES (null,'Соус Южный');
INSERT INTO ingredients VALUES (null,'Перец белый');
INSERT INTO ingredients VALUES (null,'Перец душистый');
INSERT INTO ingredients VALUES (null,'Перец молотый красный');
INSERT INTO ingredients VALUES (null,'Перец черный молотый');
INSERT INTO ingredients VALUES (null,'Майонез');
INSERT INTO ingredients VALUES (null,'Лимонная кислота');
INSERT INTO ingredients VALUES (null,'Рыбные консервы в масле');
INSERT INTO ingredients VALUES (null,'Вобла каспийская вяленая');
INSERT INTO ingredients VALUES (null,'Щука');
INSERT INTO ingredients VALUES (null,'Хек');
INSERT INTO ingredients VALUES (null,'Треска');
INSERT INTO ingredients VALUES (null,'Минтай');
INSERT INTO ingredients VALUES (null,'Морская капуста');
INSERT INTO ingredients VALUES (null,'Подсолнечник-семя');
INSERT INTO ingredients VALUES (null,'Щавель');
INSERT INTO ingredients VALUES (null,'Чеснок');
INSERT INTO ingredients VALUES (null,'Укроп');
INSERT INTO ingredients VALUES (null,'Петрушка');
INSERT INTO ingredients VALUES (null,'Лук');
INSERT INTO ingredients VALUES (null,'Томатная паста');
INSERT INTO ingredients VALUES (null,'Горошек зеленый. Консервы');
INSERT INTO ingredients VALUES (null,'Томаты (помидоры)');
INSERT INTO ingredients VALUES (null,'Свекла');
INSERT INTO ingredients VALUES (null,'Морковь');
INSERT INTO ingredients VALUES (null,'Капуста');
INSERT INTO ingredients VALUES (null,'Картофель');
INSERT INTO ingredients VALUES (null,'Огурец');
INSERT INTO ingredients VALUES (null,'Курица');
INSERT INTO ingredients VALUES (null,'Говядина');
INSERT INTO ingredients VALUES (null,'Свинина');
INSERT INTO ingredients VALUES (null,'Колбаса');
INSERT INTO ingredients VALUES (null,'Мука');
INSERT INTO ingredients VALUES (null,'Макаронные изделия');
INSERT INTO ingredients VALUES (null,'Творог');
INSERT INTO ingredients VALUES (null,'Сметана');
INSERT INTO ingredients VALUES (null,'Сливки');
INSERT INTO ingredients VALUES (null,'Ряженка');
INSERT INTO ingredients VALUES (null,'Простокваша');
INSERT INTO ingredients VALUES (null,'Молоко');
INSERT INTO ingredients VALUES (null,'Ряженка');
INSERT INTO ingredients VALUES (null,'Кефир');
INSERT INTO ingredients VALUES (null,'Сыр');
INSERT INTO ingredients VALUES (null,'Масло');
INSERT INTO ingredients VALUES (null,'Чай');
INSERT INTO ingredients VALUES (null,'Вода');

INSERT INTO units VALUES (1,'кг');
INSERT INTO units VALUES (2,'гр');
INSERT INTO units VALUES (3,'шт');
INSERT INTO units VALUES (4,'бут');
INSERT INTO units VALUES (5,'лит');
INSERT INTO units VALUES (6,'бух');